- name: Copy RabbitMQ repo to /etc/yum.repos.d/rabbitmq.repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMQ
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: Enable and start RabbitMQ
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Create RabbitMQ user and assign permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
