- name: Add the system user roboshop
  ansible.builtin.user:
    name: roboshop
    comment: "roboshop system user"
    system: true
    shell: /sbin/nologin
    home: /app

- name: Remove app directory if it exists
  ansible.builtin.file:
    state: absent
    path: /app

- name: Create a directory if it does not exist
  ansible.builtin.file:
    state: directory
    path: /app

- name: Remove the existing file
  ansible.builtin.file:
    state: absent
    path: /tmp/catalogue.zip

- name: Download catalogue app
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: Unzip the downloaded file
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes
