- name: Disable NodeJS module
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable NodeJS 20 module
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install NodeJS
  ansible.builtin.package:
    name: nodejs
    state: present
