- name: Remove masked service file if it exists
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ component }}.service"
    state: absent

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
    mode: '0644'
  notify: daemon_reload

- name: start the service
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: started

 