- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: daemon_reload

- name: Start service
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: started

 