- name: Remove masked service file if it exists
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ component }}.service"
    state: absent

- name: copy {{ component }} service
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: daemon reload

- name: start the service
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: started

 